### ISSUE TITLE
Memory leak in 5.0.1

### ISSUE THREAD

**Issue by key88sf** [DataDog/dogstatsd-ruby#182]
We are using a `Datadog::Statsd` object in a sidekiq worker. When the worker executes, we basically do this:
```
statsd = Datadog::Statsd.new("localhost", 8125)
statsd.increment(....) # specific params not included here
```

When upgrading from 4.8.3 to 5.0.1, we are seeing memory usage on the instance start to climb linearly until it finally exhausts all memory and we get a `ThreadError: can't create Thread: Resource temporarily unavailable`. We have definitively pinpointed this problem to the 5.0.1 upgrade --- there were no other changes made other than upgrading just the dogstatsd-ruby gem.

You can see the mem usage problem in the graph below:
<img width="1194" alt="Screen Shot 2021-04-21 at 5 36 50 PM" src="https://user-images.githubusercontent.com/211776/115624167-3ae24b80-a2c8-11eb-9cc9-23b938caedfb.png">
(each little dip is a deploy where we changed just one gem version. The last one is where we upgraded dogstatsd-ruby from 4.8.3 to 5.0.1).

**Comment by remeh** [comment]
Hey @key88sf 
Thank you for having reported this issue.

I suspect this may be because of some resources opened in every client that your worker is creating, since the client is never closed (#181 will add an auto-close feature on the client in 5.0.2).

Meanwhile, in your code, would it be possible to close the opened client? E.g.

```ruby
statsd = Datadog::Statsd.new("localhost", 8125)
statsd.increment(....) # specific params not included here
# ... and near the end of the code execution ...
statsd.close()
```

**Comment by key88sf** [comment]
@remeh I will try this and let you know soon. Thanks!

**Comment by ArmandoAssuncao** [comment]
I have a same issue, in version 5.x, the `sender.rb:72` create a lot of threads:
![image](https://user-images.githubusercontent.com/12402128/116720631-d3f12080-a9b2-11eb-8bd0-0ff1aca12ec4.png)

versions:
- `gem 'ddtrace', '~> 0.48.0'`
- `gem 'dogstatsd-ruby', '~> 5.0.1'`

I currently downgrade version to `4.8.3` while wait the new version.

**Comment by remeh** [comment]
Hey @ArmandoAssuncao, thanks for your comment.
Are you using DogStatsD-ruby in a Sidekiq worker manually or are you using something else? Since version `v5.x`, a thread is created when a new DogStatsD client is instantiated (and is closed when the client is closed). In your situation where we can indeed see multiple threads being created, I think that multiple clients are created and are never closed.
That's why if you manage the lifecycle of your DogStatsD clients, please ensure that they're closed when not needed anymore.

**Comment by ArmandoAssuncao** [comment]
@remeh I use gem [ddtrace](https://github.com/DataDog/dd-trace-rb) that uses the `DogStatsD-ruby` internally.

Only config that has is:

```ruby
# config/initializers/datadog.rb
if Rails.env.production?
  Datadog.configure do |c|
    c.use :sidekiq, service_name: "name_sidekiq", client_service_name: "name_sidekiq", tag_args: true
  end
end
```

Probably the ddtrace not call method `close` correctly.

**Comment by marcotc** [comment]
👋, I've created a cross issue at `ddtrace` to track this report, as it seem to related to `dogstastd-ruby` usage by `ddtrace`: https://github.com/DataDog/dd-trace-rb/issues/1491

**Comment by deepfryed** [comment]
@marcotc ran into the same issue, seeing unbounded growth with 5.0.1 and dd-trace-rb disabled (skipping the `config.use :rails, ...`). Seeing a slow growth in sender.rb threads, which seems to be the source of the memory leak.

[image](https://user-images.githubusercontent.com/23565/118354625-33545080-b5af-11eb-86c8-e4d381c7edc8.png)

downgrading to 4.8.3 results in things returning to normal

![image](https://user-images.githubusercontent.com/23565/118354556-eec8b500-b5ae-11eb-9b31-b75a6b86a9fa.png)

We've disabled APM for the time being and downgraded dogstatsd-ruby until a fix is out.

**Comment by marcotc** [comment]
Thank you for the information, @deepfryed. Are you also using Sidekiq, and had `c.use :sidekiq` in your `Datadog.configure do |c|...` block for your `ddtrace` configuration?

**Comment by deepfryed** [comment]
@marcotc not using sidekiq in the rails app, ddtrace is required but not used as noted in my comment.

**Comment by marcotc** [comment]
I've tried to reproduce this issue with both a Sidekiq and a Rails application, but with no success: both versions have the same memory profile regardless of `dogstatsd-ruby` being version `4.8.3` or `5.0.1`.

👋 @ArmandoAssuncao, given you have a clear output pointing to `sender.rb:72` being the culprit, I've [created a Sidekiq test run](https://github.com/DataDog/dd-trace-rb/compare/master...fix-statsd-resource#diff-5cec4f3b9e32a1e803ce4162ddc68ced74d61befcc787ba11ea155477e16329a) that runs the Sidekiq server and schedules 10000 jobs, but I don't see unbounded memory accumulation, nor additional threads being created.

This is likely due to a difference between what my Sidekiq server is doing, compared to yours.

Could I ask you to provide us with your Sidekiq configuration:
* Version of Sidekiq and Redis gem.
* `sidekiq.yml`
* The command executed to run Sidekiq.
* Additional "runner" information, if applicable. (e.g does it run under `puma`? If so, what's your `puma` configuration?).

Additionally, could you provide a sample Sidekiq worker class? For the worker class, let me know what kind of pattern you normally use to schedule them (e.g. delayed job, perform_after). I'd like to trigger a similar pattern myself to try to reproduce the issue.

Regarding Datadog configuration, I noticed you provided your `Datadog.configure do |c|...` block above: is that the complete block? If not, could you provide the complete block instead? Feel free to mask any private information (e.g. services names).

Still regarding `Datadog.configure`, do you have any special configuration to make it work with the Sidekiq worker process? I ask because sometimes, depending on your setup (e.g. non-Rails), you might have to manually initialize `Datadog.configure` for Sidekiq jobs to be instrumented.

Sorry for asking so much information, but I've inspected both `ddtrace` and `dogstatsd-ruby` for clues and it doesn't seem like it's possible for `ddtrace` to ever create more than 2 `dogstatsd-ruby` at any point in time. There's also no dynamic `dogstatsd-ruby` instance creation: it only happens during `Datadog.configure` calls. And days of testing with the application types suggested here yielded no reproduction.

My current priority is to fix this issue, so let me know if you can't provide the information above for any reason.

Thank you in advance!

**Comment by deepfryed** [comment]
@marcotc 

this is what we got when checking our production container running dogstatsd 5.0.1. No sidekiq, the puma (5.2.2) config has max 32 threads.

>  root@app-prod-6949448b68-vj4q6:/app# ps -eL | grep sender.rb | wc -l
> 1091

The rails (6.1) config is below

```
Datadog.configure do |c|
  # This will activate auto-instrumentation for Rails when not in test environment 
  # and enable log traceid injection
  c.use :rails, log_injection: true, database_service: 'server-postgres', cache_service: 'server-redis'
end

Datadog::Pipeline.before_flush(
  # Remove spans for /up requests
  Datadog::Pipeline::SpanFilter.new { |span| span.resource =~ /InfoController/ }
)
```

**Comment by marcotc** [comment]
Thank you, @deepfryed! This is helpful, I'm thinking puma might be an important component on this that I haven't tested with.

Are there any other references to `Datadog` gems (either `ddtrace` or `dogstatsd-ruby`) in your application's code?
Also, what version of `ddtrace` are you running?

**Comment by marcotc** [comment]
@deepfryed, I've tested my application with Puma, but still no leak.

> this is what we got when checking our production container

Correct me if I'm wrong, but you still have an environment running the problematic gem versions currently. If so, and if this is feasible for you, would you be able to add some logging around the creation of the "sender" thread:

```ruby
module DatadogStatsdSenderDebug
  def start
    if defined?(Rails.logger)
      Rails.logger.warn("Statsd thread created: #{caller}")
    else
      puts "Statsd thread created: #{caller}"
    end

    super
  end
end

require 'datadog/statsd'
Datadog::Statsd::Sender.prepend(DatadogStatsdSenderDebug)
```

I'd recommend placing this before your `Datadog.configure` block.
Feel free to modify the logging output mechanism.
This logging will be verbose, so feel free to conditionally enable this in the relevant environment for your team.

**Comment by deepfryed** [comment]
@marcotc we directly send metrics to statsd receiver. This happens during the request / response cycle to capture certain events. sanitized code snippet below:

```ruby
require 'forwardable'
require 'datadog/statsd'

module Metrics
  class Statsd
    class << self
      extend Forwardable

      def_delegators :instance,
        :increment,
        :decrement,
        :count,
        :gauge,
        :histogram,
        :timing,
        :time,
        :set,
        :event

      def instance
        Thread.current[:statsd] ||= new
      end
    end

    extend Forwardable

    def_delegators :@statsd,
      :increment,
      :decrement,
      :count,
      :gauge,
      :histogram,
      :timing,
      :time,
      :set,
      :event

    def initialize
      @statsd = Datadog::Statsd.new(host, port)
    end

    ...

  end
end
``` 

> I've tested my application with Puma, but still no leak.

I suspect this only happens at higher concurrency levels, as noted we did not catch this issue in our test / staging environment and only observed it in production under load. Perhaps you can simulate the load conditions at your end with siege or apache bench with higher concurrency matching the number of puma threads ?

**Comment by marcotc** [comment]
👋 @deepfryed, @ArmandoAssuncao, and @key88sf. If you have a chance, would you be able to try installing a version of `ddtrace` that include [some changes that might be able to reduce the thread creation #1547](https://github.com/DataDog/dd-trace-rb/pull/1547) (thus memory increases)?

```ruby
# Gemfile, replacing the existing `gem 'ddtrace'` line
source 'http://gems.datadoghq.com/prerelease-v2' do
  gem 'ddtrace', '0.50.0.only.start.runtime.when.needed.141607'
end
```

This branch has the same content as `ddtrace` [0.50.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.50.0), with the addition of changes to avoid thread creation on metrics that are not being used. So I you are running 0.50.0, this introduces the minimum amount of changes.

Let me know if this new build works for you.

**Comment by deepfryed** [comment]
sorry @marcotc - since this was spotted on a critical piece of infrastructure, we cannot deploy test releases in prod. I may have some time next week to setup a stripped down test case and try it there.

**Comment by mobilutz** [comment]
As v5.1.0 was just released yesterday, I wanted to ask if someone knows if this issue is still present in that release?

**Comment by remeh** [comment]
Hello @mobilutz 
Yes, it is still present (mentioned in the CHANGELOG), we released 5.1.0 because the flush on close will solve missing metrics for some users.
For current issue, I'm working on adding a single-thread mode for when users can't create and destroy the instance during the lifecycle of a forked process, which often happens while using job libraries or other libraries heavily relying on forks, and which is most likely part of the thread leak issue. I'll notify in this issue once it's available.

**Comment by remeh** [comment]
Hello everyone,
People having this issue should consider using the `single_thread` mode recently added into v5.2.0: [release note](https://github.com/DataDog/dogstatsd-ruby/releases/tag/v5.2.0).
Like v4.x versions, this single thread mode is not creating any companion thread to do the flush, which will avoid having issues for processes using `fork`.

**Comment by marcotc** [comment]
This issue should be addressed by the latest release of `ddtrace` (`0.51.0`), as StatsD threads are not initialized anymore by `ddtrace`.

If anyone is seeing this issue in their environment, please upgrade to `ddtrace` `>= 0.51.0` **and** `dogstastd-ruby` `>= 5.2.0`.

`ddtrace` `0.51.0` also has new safeguards that will prevent the internal initialization of affected versions of `dogstastd-ruby` (`5.0.0 <= version < 5.0.0`). Internal Statsd usage will be disabled with these affected versions, to prevent resource leaks. Tracing will continue as usual.

**Comment by key88sf** [comment]
Still seeing the same memory leaks with ddtrace 0.51.0 and dogstatsd-ruby 5.2.0

**Comment by remeh** [comment]
Hello @key88sf,

We will continue investigating this then. Since `ddtrace 0.51.0` should now use single-threaded instances of `dogstatsd-ruby`, if there is still a memory leak, I expect it to not be a thread-leak anymore. Any chance that you have the ruby error around once it has reached the limit? (or maybe you've stopped it before exhaustion)
I would like to know if you've hit the same error `ThreadError: can't create Thread: Resource temporarily unavailable`.

Also, in your workers, had you the chance to add the call to the `#close` method (and to use the `single_thread: true` mode while creating the instances)?

I'm sorry that `5.2.0` still hasn't fixed your issue, I'll continue working on fixing it!

**Comment by key88sf** [comment]
@remeh Hello - so yes the error was the same `ThreadError: can't create Thread: Resource temporarily unavailable`.

We ended up changing the code to use the `single_thread: true` mode as well as call `#close`  (and additionally to not keep an instance of Statsd around longer than needed), and that seems to have fixed the problem.

**Comment by remeh** [comment]
Hey everyone: @key88sf issue has been fixed with the `single_thread` mode and proper call to the `#close` method. I'm closing this for now.
If you encounter the same issue, please make sure to go through the [v4.x -> v5.x migration guide and v5.x common pitfalls](https://github.com/DataDog/dogstatsd-ruby/blob/master/README.md#migrating-from-v4x-to-v5x) and to use a recent version of `dogstatsd-ruby`. If you still have the same issue, please feel free to open a new issue 👍
